### ISSUE TITLE
CSS :: Hover-Effekte inkl. Input-Form

### ISSUE THREAD

**Issue by gseilheimer** [FriendsOfREDAXO/lightgallery#2]
TODO: Version 0.2

**Comment by AWqxKAWERbXo** [comment]
Wäre es nicht zielführender, eine Bibliothek ohne jQuery-Abhängigkeit zu nehmen? (z.B. https://photoswipe.com/)

**Comment by gseilheimer** [comment]
@alexplusde klar, du hast vollkommen recht. es ist auch schon veraltet.
sollte es bereits etwas vergleichbares geben, dann archiviere ich es einfach?
alternativ habe ich ab mitte september zeit für die pwa demo und für eine anpassung an diesem addon?

**Comment by AWqxKAWERbXo** [comment]
Würde sagen, das wäre dann ein separates Projekt. Habe mich gestern mit photoswipe auseinandergesetzt. Ist schon nicht ohne. Bin doch sehr vom Denken noch in jQuery...

**Comment by gseilheimer** [comment]
Ja. Ein PlugIn mit reinen JS-Code wäre zukünftig besser. Es wird hier auch keine weiteren Änderungen geben.
